verif/coverage/operand_isolation_coverage.sv
verif/coverage/operand_isolation_transition_coverage.sv
verif/coverage/operand_isolation_integration_coverage.sv
verif/coverage/operand_isolation_coverage_bind.sv
