export DESIGN_NAME = counter
export PLATFORM = $(OPENROAD_PLATFORM)
export VERILOG_FILES = $(REPO_ROOT)/rtl/counter.sv
export SDC_FILE = $(SYNTHESIS_CONSTRAINT_FILE)
export CORE_UTILIZATION = 35
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 2
